### ISSUE TITLE
请教一下如何修改字体

### ISSUE THREAD

**Issue by fwrite0920** [showzeng/Minimalism#1]
你的博客的字体比demo的字体好看不少呀，请问怎么修改字体呢

**Comment by ZoeyWoohoo** [comment]
这个其实是因为考虑到会有版权问题，所以没放到主题里。

其实就是加载一下字体资源然后导进入：

```css
/* xxx font face start */
@font-face {
    font-family: 'xxx-webfont';
    src: url('https://xxx.xxx.xxx/font/xxx-webfont.woff2') format('woff2'),
         url('https://xxx.xxx.xxx/font/xxx-webfont.woff') format('woff'),
         url('https://xxx.xxx.xxx/font/xxx-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}
/* xxx font face end */
```

然后设置 font-family：

```css
html {
  font-family: xxx-webfont, Monaco, Helvetica, Tahoma, Arial, STXihei, "华文细黑",
  "Microsoft YaHei", "微软雅黑", SimSun, "宋体", Heiti, "黑体", sans-serif;
}
```

把自己定义的字体放在首位 (因为个人比较喜欢 Monaco 字体 (英文)，其实这里主要是为了非 Mac 用户)，如果想了解这一部分可以参考一下这个链接：[CSS3 font-face](https://www.w3cplus.com/content/css3-font-face)

所以你就可以下载自己喜欢的字体，然后制作成各种格式的字体文件，导入就 OK 啦。这里有一个在线的工具推荐给你：[Webfonot generator](https://www.fontsquirrel.com/tools/webfont-generator)
